nomeUsuario = (input("Olá, informe seu nome: "))
nomeRua = (input("Agora informe o nome da sua rua: "))
cep = (input ("Informe seu CEP: "))
nomeBairro = (input("Informe o nome do seu bairro: "))
nomeCidade = (input("Informe o nome da sua cidade: "))
nomeEstado = (input("Informe o nome do seu estado: "))
print("Nome: " + nomeUsuario)
print("Endereço: " + nomeRua)
print("CEP: " + cep)
print("Bairro: " + nomeBairro)
print("Cidade: " + nomeCidade)
print("Estado: " + nomeEstado)
print("Obrigado por compartilhar essas informações!")
